#pragma once

class m_IDirect3DDevice2 : public dx6::IDirect3DDevice2, public AddressLookupTableObject
{
private:
	dx6::IDirect3DDevice2 *ProxyInterface;

public:
	m_IDirect3DDevice2(dx6::IDirect3DDevice2 *aOriginal, void *temp) : ProxyInterface(aOriginal)
	{
		ProxyAddressLookupTable.SaveAddress(this, ProxyInterface);
	}
	~m_IDirect3DDevice2()
	{
		ProxyAddressLookupTable.DeleteAddress(this);
	}

	dx6::IDirect3DDevice2 *GetProxyInterface() { return ProxyInterface; }

	/*** IUnknown methods ***/
	STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID * ppvObj);
	STDMETHOD_(ULONG, AddRef)(THIS);
	STDMETHOD_(ULONG, Release)(THIS);

	/*** dx6::IDirect3DDevice2 methods ***/
	STDMETHOD(GetCaps)(THIS_ dx6::LPD3DDEVICEDESC, dx6::LPD3DDEVICEDESC);
	STDMETHOD(SwapTextureHandles)(THIS_ dx6::LPDIRECT3DTEXTURE2, dx6::LPDIRECT3DTEXTURE2);
	STDMETHOD(GetStats)(THIS_ dx6::LPD3DSTATS);
	STDMETHOD(AddViewport)(THIS_ dx6::LPDIRECT3DVIEWPORT2);
	STDMETHOD(DeleteViewport)(THIS_ dx6::LPDIRECT3DVIEWPORT2);
	STDMETHOD(NextViewport)(THIS_ dx6::LPDIRECT3DVIEWPORT2, dx6::LPDIRECT3DVIEWPORT2*, DWORD);
	STDMETHOD(EnumTextureFormats)(THIS_ dx6::LPD3DENUMTEXTUREFORMATSCALLBACK, LPVOID);
	STDMETHOD(BeginScene)(THIS);
	STDMETHOD(EndScene)(THIS);
	STDMETHOD(GetDirect3D)(THIS_ dx6::LPDIRECT3D2*);
	STDMETHOD(SetCurrentViewport)(THIS_ dx6::LPDIRECT3DVIEWPORT2);
	STDMETHOD(GetCurrentViewport)(THIS_ dx6::LPDIRECT3DVIEWPORT2 *);
	STDMETHOD(SetRenderTarget)(THIS_ LPDIRECTDRAWSURFACE, DWORD);
	STDMETHOD(GetRenderTarget)(THIS_ LPDIRECTDRAWSURFACE *);
	STDMETHOD(Begin)(THIS_ dx6::D3DPRIMITIVETYPE, D3DVERTEXTYPE, DWORD);
	STDMETHOD(BeginIndexed)(THIS_ dx6::D3DPRIMITIVETYPE, D3DVERTEXTYPE, LPVOID, DWORD, DWORD);
	STDMETHOD(Vertex)(THIS_ LPVOID);
	STDMETHOD(Index)(THIS_ WORD);
	STDMETHOD(End)(THIS_ DWORD);
	STDMETHOD(GetRenderState)(THIS_ dx6::D3DRENDERSTATETYPE, LPDWORD);
	STDMETHOD(SetRenderState)(THIS_ dx6::D3DRENDERSTATETYPE, DWORD);
	STDMETHOD(GetLightState)(THIS_ dx6::D3DLIGHTSTATETYPE, LPDWORD);
	STDMETHOD(SetLightState)(THIS_ dx6::D3DLIGHTSTATETYPE, DWORD);
	STDMETHOD(SetTransform)(THIS_ dx6::D3DTRANSFORMSTATETYPE, dx6::LPD3DMATRIX);
	STDMETHOD(GetTransform)(THIS_ dx6::D3DTRANSFORMSTATETYPE, dx6::LPD3DMATRIX);
	STDMETHOD(MultiplyTransform)(THIS_ dx6::D3DTRANSFORMSTATETYPE, dx6::LPD3DMATRIX);
	STDMETHOD(DrawPrimitive)(THIS_ dx6::D3DPRIMITIVETYPE, D3DVERTEXTYPE, LPVOID, DWORD, DWORD);
	STDMETHOD(DrawIndexedPrimitive)(THIS_ dx6::D3DPRIMITIVETYPE, D3DVERTEXTYPE, LPVOID, DWORD, LPWORD, DWORD, DWORD);
	STDMETHOD(SetClipStatus)(THIS_ dx6::LPD3DCLIPSTATUS);
	STDMETHOD(GetClipStatus)(THIS_ dx6::LPD3DCLIPSTATUS);
};
